GET  http://localhost:3001/tweets
Content-Type: application/json

### 

GET  http://localhost:3001/retweets
Content-Type: application/json

### 

POST  http://localhost:3001/tweets
Content-Type: application/json

{
    "username":"david",
    "content":"Hey everyone im new in twitter :)"
}

###


POST  http://localhost:3001/tweets/likes/8
Content-Type: application/json

{
    "username":"Daniel"
}

### 

POST  http://localhost:3001/tweets/retweet/8
Content-Type: application/json

{
    "username":"David"
}